library(leafem)
library(leaflet)
library(leaflet.opacity)
library(shiny)
library(shinyWidgets)
library(raster)
library(rgdal)
library(pdftools)
library(scales)
library(tidyverse)
library(RANN)

source('/Users/kyledoherty/mpgPostdoc/projects/ecology_tools/app/global.R')
source('/Users/kyledoherty/mpgPostdoc/projects/ecology_tools/app/ui.R')
source('/Users/kyledoherty/mpgPostdoc/projects/ecology_tools/app/server.R')

shinyApp(ui = ui, server = server)